name: tms
description: Team Management System for FLL

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.0+0 # this is replaced in azure pipelines during release

# First submission required before we can begin publishing to the windows store
msix_config:
  display_name: TMS Client
  publisher_display_name: A Loose Screw
  identity_name: 20448ALooseScrew.TMSClient
  publisher: CN=E961EDDD-C8AE-489C-8DEE-15C89A72602A
  msix_version: 0.0.0.0 # this is replaced in azure pipelines during release
  store: true

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  web_socket_channel: ^2.3.0
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  http: ^0.13.5
  uuid: ^3.0.7
  multicast_dns: ^0.3.2+3
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.5
  fl_chart: ^0.61.0
  provider: ^6.0.5
  data_table_2: ^2.4.2
  tuple: ^2.0.1
  shared_preferences: ^2.1.0
  fast_rsa: ^3.5.6
  enum_to_string: ^2.0.1
  logger: ^1.3.0
  flutter_dotenv: ^5.1.0
  file_picker: ^5.2.10
  csv: ^5.0.2
  just_audio: ^0.9.35
  syncfusion_flutter_pdfviewer: ^21.2.10
  multiselect: ^0.1.0
  dropdown_search: ^5.0.6
  intl: ^0.18.1
  accordion: ^2.6.0
  path_provider: ^2.1.1
  file_saver: ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# run -> `flutter pub run flutter_launcher_icons` to generate icons
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logos/TMS_LOGO_ICON_SQUARE.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Radioland
      fonts:
        - asset: assets/fonts/RADIOLAND.TTF
        - asset: assets/fonts/RADIOLANDSLIM.ttf

    - family: lcdbold
      fonts:
        - asset: assets/fonts/LCDBOLD.ttf
    
    - family: Digital7
      fonts:
        - asset: assets/fonts/DIGITAL7.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/audio/

    - packages/fast_rsa/web/assets/worker.js
    - packages/fast_rsa/web/assets/wasm_exec.js
    - packages/fast_rsa/web/assets/rsa.wasm

    - .env