jobs:
# - job: AIO_Docker
#   pool:
#     vmImage: ubuntu-latest
#   steps:
#     - template: pre-steps.yml
#     - script: |
#         sudo apt-get update && sudo apt-get install -qq -y musl-tools musl-dev
#     - task: Cargo@1
#       inputs:
#         cargoCommand: 'build --release --target x86_64-unknown-linux-musl'
#         cargoWorkingDir: './server'
#         verbose: false
#     - task: FlutterBuild@0
#       inputs:
#         target: 'web'
#         projectDirectory: './tms'

#     # Build docker image
#     - task: CmdLine@2
#       inputs:
#         script: 'docker-compose build --pull'

#     # Publish docker image
#     - task: CmdLine@2
#       condition: and(succeeded(), eq(variables.isPublishable, 'true'))
#       inputs:
#         script: 'docker login -u cjbuchel -p $(TMS-TOKEN); docker-compose push; docker logout'


- job: windows
  pool:
    vmImage: 'windows-2022'
  steps:
    - template: pre-steps.yml
    - template: build-desktop.yml
      parameters:
        target: windows

# - job: macos
#   pool:
#     vmImage: 'macOs-12'
#   steps:
#     - template: pre-steps.yml
#     - template: build-desktop.yml
#       parameters:
#         target: macos

# - job: linux
#   pool:
#     vmImage: 'ubuntu-22.04'
#   steps:
#     - template: pre-steps.yml
#     - template: build-desktop.yml
#       parameters:
#         target: linux

# - job: android
#   pool:
#     vmImage: 'ubuntu-22.04'
#   steps:
#     - template: pre-steps.yml
#     - template: build-mobile.yml
#       parameters:
#         target: apk

# - job: ios
#   pool:
#     vmImage: 'macOs-12'
#   steps:
#     - template: pre-steps.yml
#     - template: build-mobile.yml
#       parameters:
#         target: ios