[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[taarget.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

[taarget.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=+crt-static"]