# Azure test/publish

trigger:
- master 
- docker-publish
- docker-publish-dev

resources: 
- repo: self

jobs:
- job: AIO_Docker
  displayName: Build and Publish an all in one package for TMS
  pool:
    vmImage: ubuntu-latest
  steps:
    # - template: azure-steps.yml
    - task: FlutterInstall@0
      inputs:
        mode: 'auto'
        channel: 'stable'
        version: 'latest'

    - task: FlutterBuild@0
      inputs:
        target: 'web'
        projectDirectory: './tms'