trigger:
- master
- docker-publish

resources:
- repo: self

variables:
  isPublishable: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/docker-publish'))]
  tag: '$(Build.BuildId)'

jobs:
- job: BuildPublish
  displayName: Build & Publish CJ-MS
  pool:
    vmImage: ubuntu-latest
  steps:

  - task: NodeTool@0
    inputs:
      versionSpec: latest
    displayName: 'Install Node.js'
  - script: |
    yarn install
    yarn run build

  - task: CmdLine@2
    inputs:
      script: |
      docker -v
      docker-compose -v
      docker-compose build --pull

  - task: CmdLine@2
    condition: and(succeeded(), eq(variables.isPublishable, 'true'))
    inputs:
      script: |
      docker login -u cjbuchel -p $(cjms-token)
      docker-compose push
      docker logout