# Azure test/publish
# https://levelup.gitconnected.com/integrate-your-flutter-application-with-azure-devops-and-app-center-6e5e5ee4a53

trigger:
- master 
- docker-publish
- publish

resources: 
- repo: self

variables: 
- group: apple-variables
- template: './azure-pipelines/vars.yml'
- name: isPublishable
  value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/publish'))]

  # docker variables
- name: dockerRepository
  value: 'cjbuchel/tms'
- name: dockerfilePath
  value: '**/Dockerfile'
- name: dockerRegistryServiceConnection
  value: 'CJBuchel-Dockerhub1'

stages:
- stage: Build
  jobs:
  - template: './azure-pipelines/build-stage/build-stage.yml'

- stage: Release
  dependsOn: Build
  condition: and(succeeded(), eq(variables['isPublishable'], true))
  jobs:
  - template: './azure-pipelines/release-stage/release-stage.yml'