
resources: 
- repo: self

variables:
- group: 'apple-variables'

stages:
- stage: Build
  displayName: 'Generate & Build'
  jobs:
    - template: azure-pipelines/build-stage.yml


# - stage: Build
# - stage: Test
# - stage: Release