trigger:
- master
- docker-publish

resources:
- repo: self

variables:
  isPublishable: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/docker-publish'))]
  tag: '$(Build.BuildId)'

jobs:
- job: BuildAndPublish
  displayName: Build & Publish CJ-MS
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: docker -v
  # - task: NodeTool@0

  # - task: Docker@2
  #   displayName: Build Image
  #   inputs:
  #     command: build
  #     Dockerfile: '**/Dockerfile'
  #     tags: |
  #       latest
  #       $(tag)

# - job: Publish
#   displayName: Publish JMS
#   condition: and(succeeded(), eq(variables.isPublishable, 'true'))
#   pool:
#     vmImage: ubuntu-latest
#   steps:
#     - task: Docker@2
#       displayName: Publish Image
#       inputs:
#         command: buildAndPush
#         containerRegistry: CJBuchel-Dockerhub1
#         Dockerfile: '**/Dockerfile'
#         tags: |
#           latest
#           $(tag)
#     - task: Docker@2
#       displayName: Logout
#       inputs:
#         command: logout
#         containerRegistry: CJBuchel-Dockerhub1