# Azure test/publish

trigger:
- master 
- docker-publish
- docker-publish-dev

resources: 
- repo: self

strategy: 
  matrix: 

    # Latest variants
    windows-latest:
      imageName: 'windows-latest'
      rustup_toolchain: stable
    mac-latest:
      imageName: 'macOS-latest'
      rustup_toolchain: stable
    linux-latest:
      imageName: 'ubuntu-latest'
      rustup_toolchain: stable

    # Stable variants
    windows-stable:
      imageName: 'windows-2019'
      rustup_toolchain: stable
    mac-stable:
      imageName: 'macOs-11'
      rustup_toolchain: stable
    linux-stable:
      imageName: 'ubuntu-20.04'
      rustup_toolchain: stable

pool:
  vmImage: $(imageName)

steps:
  - template: azure-steps.yml
  - script: cargo build --all
    workingDirectory: './server'


# jobs:
# - job: AIO-Docker
#   displayName: Build & Publish the docker image
#   pool:
#     vmImage: ubuntu-latest
#   steps:

#   # Init
#   - displayName: Git Initializing
#   - script: git submodule update --init --recursive
#   - script: git submodule update --remote --recursive -f

#   # Install requirements for rust
#   - displayName: Rust Install
#   - script: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
#   - script: 