# Azure test/publish
# https://levelup.gitconnected.com/integrate-your-flutter-application-with-azure-devops-and-app-center-6e5e5ee4a53

trigger:
- master 
- docker-publish
- docker-publish-dev

resources: 
- repo: self


jobs:
- job: AIO_Docker
  pool:
    vmImage: ubuntu-latest
  steps:
    - template: './azure/pre-steps.yml'
    - script: |
        sudo apt-get update && sudo apt-get install -qq -y musl-tools musl-dev
    - task: Cargo@1
      inputs:
        cargoCommand: 'build --release --target x86_64-unknown-linux-musl'
        cargoWorkingDir: './server'
        verbose: false
    - task: FlutterBuild@0
      inputs:
        target: 'web'
        projectDirectory: './tms'

- job: CrossCI
  strategy: 
    matrix: 

      # Desktops
      windows-stable:
        imageName: 'windows-2019'
        flutter-stable: 'windows'
      macOs-stable:
        imageName: 'macOs-12'
        flutter-stable: 'macOs'
      linux-stable:
        imageName: 'ubuntu-22.04'
        flutter-stable: 'linux'

      # Mobiles
      mobile-stable:
        imageName: 'macOs-11'
        flutter-target: 'mobile'
  pool:
    vmImage: $(imageName)
  steps:
    - template: './azure/pre-steps.yml'
    - script: |
        sudo apt-get install -qq -y clang ninja-build libgtk-3-dev
      condition: eq( variables['Agent.OS'], 'Linux' )
    - task: FlutterBuild@0
      inputs:
        target: $(flutter-target)
        projectDirectory: './tms'
        iosCodesign: false