# Azure test/publish

trigger:
- master 
- docker-publish
- docker-publish-dev

resources: 
- repo: self

jobs:
- job: AIO-Docker
  displayName: Build & Publish the docker image
  pool:
    vmImage: ubuntu-latest
  steps:
    - template: azure-steps.yml
    - task: FlutterBuild@0
      inputs:
        target: 'all'
        projectDirectory: './tms'