trigger:
- master
- docker-publish

resources:
- repo: self

variables:
  isPublishable: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/docker-publish'))]
  tag: '$(Build.BuildId)'

jobs:
- job: BuildPublish
  displayName: Build & Publish CJ-MS
  pool:
    vmImage: ubuntu-latest
  steps:

  - script: ls -a
  # - script: ./docker-create-env.sh
  
  - task: ShellScript@2
    inputs:
      scriptPath: '$(System.DefaultWorkingDirectory)/docker-create-env.sh'
      failOnStandardError: true

  # Build Node App
  - task: NodeTool@0
    inputs:
      versionSpec: '>=10.x'
    displayName: 'Install Node.js'
  - script: npm install -g yarn
  - script: yarn install
  - script: yarn run build
  
  - script: ls -a

  # Build Docker app
  - task: CmdLine@2
    inputs:
      script: 'docker-compose build --pull'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      failOnStderr: true

  # Publish Docker app
  - task: CmdLine@2 
    condition: and(succeeded(), eq(variables.isPublishable, 'true'))
    inputs:
      script: 'docker login -u cjbuchel -p $(cjms-token); docker-compose push; docker logout'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      failOnStderr: true