# Azure test/publish
# https://levelup.gitconnected.com/integrate-your-flutter-application-with-azure-devops-and-app-center-6e5e5ee4a53

trigger:
- master 
- docker-publish
- publish

resources: 
- repo: self



variables: 
  - template: './azure/env.yaml'
  - name: isPublishable
    value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/publish'))]


jobs:
- job: AIO_Docker
  pool:
    vmImage: ubuntu-latest
  steps:
    - template: './azure/pre-steps.yml'
    - script: |
        sudo apt-get update && sudo apt-get install -qq -y musl-tools musl-dev
    - task: Cargo@1
      inputs:
        cargoCommand: 'build --release --target x86_64-unknown-linux-musl'
        cargoWorkingDir: './server'
        verbose: false
    - task: FlutterBuild@0
      inputs:
        target: 'web'
        projectDirectory: './tms'

    # Build docker image
    - task: CmdLine@2
      inputs:
        script: 'docker-compose build --pull'

    # Publish docker image
    - task: CmdLine@2
      condition: and(succeeded(), eq(variables.isPublishable, 'true'))
      inputs:
        script: 'docker login -u cjbuchel -p $(TMS-TOKEN); docker-compose push; docker logout'

    # Publish github release
    - template: './azure/github-release.yml'

- job: CrossCI
  strategy: 
    matrix: 

      # Desktops
      windows-stable:
        imageName: 'windows-2019'
        flutter-stable: 'windows'
      macOs-stable:
        imageName: 'macOs-12'
        flutter-stable: 'macOs'
      linux-stable:
        imageName: 'ubuntu-22.04'
        flutter-stable: 'linux'

      # Mobiles
      mobile-stable:
        imageName: 'macOs-12'
        flutter-target: 'mobile'
  pool:
    vmImage: $(imageName)
  steps:
    - template: './azure/pre-steps.yml'
    - script: |
        sudo apt-get install -qq -y clang ninja-build libgtk-3-dev
      condition: eq( variables['Agent.OS'], 'Linux' )
    - task: FlutterBuild@0
      inputs:
        target: $(flutter-target)
        projectDirectory: './tms'
        iosCodesign: false