# Azure test/publish

trigger:
- master 
- docker-publish
- docker-publish-dev

resources: 
- repo: self

jobs:
- job: AIO_Docker
  pool:
    vmImage: ubuntu-latest
  steps:
    # - template: './azure/pre-steps.yml'
    - script: |
        apt-get update && apt-get install -qq -y 
        musl-tools musl-dev
    - task: Cargo@1
      inputs:
        cargoCommand: 'build --release --target x86_64-unknown-linux-musl'
        cargoWorkingDir: './server'
        verbose: false
    - task: FlutterBuild@0
      inputs:
        target: 'web'
        projectDirectory: './tms'

- job: CrossCI
  strategy: 
    matrix: 

      # Desktops
      windows-latest:
        imageName: 'windows-latest'
        flutter-target: 'windows'
      macOs-latest:
        imageName: 'macOs-latest'
        flutter-target: 'macOs'
      linux-latest:
        imageName: 'ubuntu-latest'
        flutter-target: 'linux'

      # Mobiles
      mobile-latest:
        imageName: 'macOs-latest'
        flutter-target: 'mobile'
  pool:
    vmImage: $(imageName)
  steps:
    - template: './azure/pre-steps.yml'
    - script: |
        sudo apt-get install -qq -y 
        clang ninja-build libgtk-3-dev
      condition: eq( variables['Agent.OS'], 'Linux' )
    - task: FlutterBuild@0
      inputs:
        target: $(flutter-target)
        projectDirectory: './tms'