trigger:
- master
- docker-publish

resources:
- repo: self

variables:
  isPublishable: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/docker-publish'))]
  tag: '$(Build.BuildId)'

jobs:
- job: Build
  displayName: Build CJ-MS
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: docker -v
  - script: docker-compose -v
  - script: docker-compose build --pull

- job: Publish
  displayName: Publish CJ-MS
  dependsOn: Build
  condition: and(succeeded(), eq(variables.isPublishable, 'true'))
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: docker -v
  - script: docker-compose -v
  - script: docker-compose push -u cjbuchel -p $(cjms-token)