# Azure test/publish

trigger:
- master 
- docker-publish
- docker-publish-dev

resources: 
- repo: self

jobs:
- job: AIO_Docker
  pool:
    vmImage: ubuntu-latest
  steps:
    - template: './azure/pre-steps.yml'
    # @TODO, install muls for server docker deploy
    - script: apt update && apt install -y musl-tools musl-dev
    - task: FlutterBuild@0
      inputs:
        target: 'web'
        projectDirectory: './tms'

- job: CrossCI
  strategy: 
    matrix: 

      # Desktops
      windows-latest:
        imageName: 'windows-latest'
        flutter-target: 'windows'
      macOs-latest:
        imageName: 'macOs-latest'
        flutter-target: 'macOs'
      linux-latest:
        imageName: 'ubuntu-latest'
        flutter-target: 'linux'

      # Mobiles
      ios-latest:
        imageName: 'macOs-latest'
        flutter-target: 'mobile'
  pool:
    vmImage: $(imageName)
  steps:
    - template: './azure/pre-steps.yml'
    - task: FlutterBuild@0
      inputs:
        target: $(flutter-target)
        projectDirectory: './tms'