trigger:
- master
- docker-publish

resources:
- repo: self

variables:
  isPublishable: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/docker-publish'))]
  tag: '$(Build.BuildId)'

jobs:
- job: BuildPublish
  displayName: Build & Publish CJ-MS
  pool:
    vmImage: ubuntu-latest
  steps:

  # Build Node App
  - task: NodeTool@0
    inputs:
      versionSpec: '>=10.x'
    displayName: 'Install Node.js'
  - script: npm install -g yarn
  - script: yarn install
  - script: yarn run build

  # Build Docker app
  - task: CmdLine@2
    inputs:
      script: docker-compose build --pull

  # Publish Docker app
  - task: CmdLine@2
    condition: and(succeeded(), eq(variables.isPublishable, 'true'))
    inputs:
      script: docker login -u cjbuchel -p $(cjms-token); docker-compose push; docker logout