# Azure test/publish
# https://levelup.gitconnected.com/integrate-your-flutter-application-with-azure-devops-and-app-center-6e5e5ee4a53

trigger:
- master 
- publish

resources: 
- repo: self

variables: 
- group: apple-variables
- template: './azure-pipelines/vars.yml'
- name: isPublishable
  value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/publish'))]
- name: isIosPublishable
  value: $[eq(variables['Build.SourceBranch'], 'refs/heads/publish')]

  # docker variables
- name: dockerRepository
  value: 'cjbuchel/tms'
- name: dockerfilePath
  value: '**/Dockerfile'
- name: dockerRegistryServiceConnection
  value: 'CJBuchel-Dockerhub1'

# Flutter cache variables
- name: FLUTTER_ROOT
  value: $(Agent.ToolsDirectory)/flutter # or the path to your flutter sdk
- name: PUB_CACHE
  value: $(Pipeline.Workspace)/.pub-cache

stages:
- stage: Build
  jobs:
  - template: './azure-pipelines/build-stage/build-stage.yml'

- stage: Release
  dependsOn: Build
  condition: and(succeeded(), eq(variables['isPublishable'], true))
  jobs:
  - template: './azure-pipelines/release-stage/release-stage.yml'