# Azure test/publish
# https://levelup.gitconnected.com/integrate-your-flutter-application-with-azure-devops-and-app-center-6e5e5ee4a53

trigger:
- master 
- docker-publish
- publish

resources: 
- repo: self

variables: 
- group: apple-variables
- template: './azure/vars.yml'
- name: isPublishable
  value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/publish'))]


stages:
- stage: Build
  jobs:
  - template: './azure/build-stage.yml'

- stage: Release
  dependsOn: Build
  condition: and(succeeded('Build'), eq(variables.isPublishable, 'true'))
  jobs:
  - job: PublishReleases
    pool:
      vmImage: 'macOs-latest'
    steps:
      - template: './azure/github-release.yml'
        parameters:
          version: ${{variables.version}}