# Azure test/publish
# https://levelup.gitconnected.com/integrate-your-flutter-application-with-azure-devops-and-app-center-6e5e5ee4a53

trigger:
- master 
- docker-publish
- publish

resources: 
- repo: self

variables: 
- template: './azure/vars.yml'
- name: isPublishable
  value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/publish'))]


stages:
- stage: Build
  jobs:
  - template: './azure/build-stage.yml'

- stage: Release
  condition: eq(variables.isPublishable, 'true')
  jobs:
  - job: GithubRelease
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: github-release.yml
        parameters:
          version: ${{variables.version}}