services:
  cjms-latest:
    container_name: cjms
    image: 'cjbuchel/cjms:latest'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '2000-3000:2000-3000'
      - '37017:27017'

  cjms-version:
    container_name: cjms-v
    image: 'cjbuchel/cjms:${TAG}'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '2000-3000:2000-3000'
      - '37017:27017'