services:
  tms-latest:
    container_name: tms
    image: 'cjbuchel/tms:latest'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      - '2121:2121'
      - '2122:2122'
      - '5353:5353'