[package]
name = "tms-schedule-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"

[dependencies.tms-infra]
path = "../tms-infra"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html