
jobs:
- job: Docker
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: ./build-steps/env-setup-steps.yml
    - template: ./build-steps/setup-rust-steps.yml
    - template: ./build-steps/setup-flutter-steps.yml
    - template: ./build-steps/build-docker-steps.yml

# - job: IOS
#   pool:
#     vmImage: 'macOs-12'
#   steps:
#     - template: ./build-steps/env-setup-steps.yml
#     # - template: ./build-steps/setup-rust-steps.yml
#     - template: ./build-steps/setup-flutter-steps.yml
#     - template: ./build-steps/build-ios-steps.yml