
jobs:
- job: Docker
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: ./build-steps/env-setup-steps.yml
    - template: ./build-steps/setup-rust-steps.yml
    - template: ./build-steps/setup-flutter-steps.yml
    - template: ./build-steps/build-docker-steps.yml

- job: IOS
  pool:
    vmImage: 'macOs-12'
  steps:
    - template: ./build-steps/env-setup-steps.yml
    - template: ./build-steps/setup-flutter-steps.yml
    - template: ./build-steps/build-ios-steps.yml

- job: Android
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: ./build-steps/env-setup-steps.yml
    - template: ./build-steps/setup-flutter-steps.yml
    - template: ./build-steps/build-android-steps.yml

- job: Client_Windows
  pool:
    vmImage: 'windows-latest'
  steps:
    - template: ./build-steps/env-setup-steps.yml
    - template: ./build-steps/setup-flutter-steps.yml
    - template: ./build-steps/build-client-windows-steps.yml

- job: Server_Windows
  pool:
    vmImage: 'windows-latest'
  steps:
    - template: ./build-steps/env-setup-steps.yml
    - template: ./build-steps/setup-rust-steps.yml
    - template: ./build-steps/build-server-windows-steps.yml

- job: Server_Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: ./build-steps/env-setup-steps.yml
    - template: ./build-steps/setup-rust-steps.yml
    - template: ./build-steps/build-server-linux-steps.yml

# - job: Server_MacOs
#   pool:
#     vmImage: 'macOs-12'
#   steps:
#     - template: ./build-steps/env-setup-steps.yml
#     - template: ./build-steps/setup-rust-steps.yml
#     - template: ./build-steps/build-server-macos-steps.yml