
jobs:
- job: Build_AIO_Docker
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: ./build-steps/env-setup-steps.yml
    - template: ./build-steps/setup-rust-steps.yml
    - template: ./build-steps/setup-flutter-steps.yml

    - task: Cargo@1
      displayName: 'Build Rust Server'
      inputs:
        cargoCommand: 'build --target x86_64-unknown-linux-musl --release'
        cargoWorkingDir: './server'
        verbose: true
    
    - task: FlutterBuild@0
      displayName: 'Build Flutter Client for Web'
      inputs:
        target: 'web'
        projectDirectory: './client'

    #  Build the docker image
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: build
        Dockerfile: $(dockerfilePath)
        repository: $(dockerRepository)
        tags: |
          $(version)
          latest
    
    # save the image to the artifact staging directory
    - script: docker save -o $(Build.ArtifactStagingDirectory)/docker_image.tar $(dockerRepository):$(version)
      displayName: 'Save Docker Image as Tarball'

    # publish the artifact
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact: docker_image'
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)/docker_image.tar
        ArtifactName: docker_image
        publishLocation: container