[package]
name = "tms_schedule_handler"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
log = "0.4.21"
regex = "1.10.4"

[dependencies.tms_infra]
path = "../tms_infra"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html