#
# This file contains the steps to generate the Dart code from the Rust code.
#
steps:
  # run the codegen
  - script: flutter_rust_bridge_codegen generate --dart-entrypoint-class-name TmsRustLib --rust-input crate::infra --rust-root tms-infra --dart-output tms-client/lib/generated
    displayName: 'Run Rust to Dart Codegen'
  # run the wasm pre codegen
  - script: wasm-pack build tms-infra --target no-modules --out-dir tms-client/web/pkg --no-typescript --out-name tms_infra --dev -- -Z build-std=std,panic_abort
    displayName: 'Run Wasm Pre-Codegen'
  # run the wasm codegen
  - script: (cd tms-client && dart run flutter_rust_bridge build-web --dart-root . --rust-root ../tms-infra)
    displayName: 'Run Wasm Codegen (Unix)'
    condition: ne(variables['Agent.OS'], 'Windows_NT')
  # run the wasm codegen (windows)
  - powershell: |
      cd tms-client
      dart run flutter_rust_bridge build-web --dart-root . --rust-root ..\tms-infra
    displayName: 'Run Wasm Codegen (Windows)'
    condition: eq(variables['Agent.OS'], 'Windows_NT')