parameters:
  - name: cargoPath
    default: $(HOME)/.cargo
  - name: rustupPath
    default: $(HOME)/.rustup

# 
# Caching for Rust dependencies and build artifacts.
# 
steps:
  - task: Cache@2
    inputs:
      key: 'cargo-registry | "$(Agent.OS)" | $(Build.SourcesDirectory)/Cargo.lock'
      restoreKeys: 'cargo-registry | "$(Agent.OS)"'
      path: $(cargoPath)/registry
    displayName: 'Cache Cargo Registry'

  - task: Cache@2
    inputs:
      key: 'cargo-bin | "$(Agent.OS)" | $(Build.SourcesDirectory)/Cargo.lock'
      restoreKeys: 'cargo-bin | "$(Agent.OS)"'
      path: $(cargoPath)/bin
    displayName: 'Cache Cargo Bin'

  - task: Cache@2
    inputs:
      key: 'rust-toolchain | "$(Agent.OS)" | $(rustc -V)'
      restoreKeys: 'rust-toolchain | "$(Agent.OS)"'
      path: $(rustupPath)/.rustup/toolchains
    displayName: 'Cache Rust Toolchain'

  # Cache Cargo build
  - task: Cache@2
    inputs:
      key: 'cargo-build | "$(Agent.OS)" | $(Build.SourcesDirectory)/Cargo.lock'
      restoreKeys: 'cargo-build | "$(Agent.OS)"'
      path: $(Build.SourcesDirectory)/target
    displayName: 'Cache Cargo Build'
