steps:
  - script: |
      echo Mac OS version:
      sw_vers -productVersion
      echo Installed Xcode versions:
      ls /Applications | grep 'Xcode'
      echo currently selected xcode:
      xcrun xcode-select --print-path
      echo selecting latest xcode...
      sudo xcode-select -s /Applications/Xcode_15.2.app
      xcrun xcode-select --print-path
      xcodebuild -version
    displayName: 'Select Xcode Version'

  - task: Xcode@5
    displayName: "Generate IPA"
    inputs:
      # xcode version 15
      xcodeVersion: '15'

      # build options
      actions: 'build'
      xcWorkspacePath: '$(Build.SourcesDirectory)/tms-client/ios/Runner.xcworkspace'
      scheme: 'Runner'
      sdk: 'iphoneos'
      configuration: 'release'

      # package options
      packageApp: true

      # signing
      signingOption: 'manual'
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'  

      # advanced
      useXcpretty: false