[package]
name = "tms-infra"
version = "0.1.0"
edition = "2021"
build = "build/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
infra-schema = { path = "infra-schema" }

[build-dependencies]
serde_json = "^1.0"
schemars = "^0.8"
infra-schema = { path = "infra-schema" }