[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "^1.36", features = ["full"] }
tokio-stream = "^0.1"
log = "0.4.21"
http = "1.1.0"
mime_guess = "2.0.4"
rcgen = "0.13.0"
local-ip-address = "0.6.1"
log4rs = "1.3.0"
structopt = "0.3.26"
warp = "^0.3"

[dependencies.database]
path = "../database"
