[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "^1.36", features = ["full"] }
tokio-stream = "^0.1"
warp = { version="^0.3", features = ["tls"] }
pretty_env_logger = { version = "^0.5" }
log = "0.4.21"
http = "1.1.0"
mime_guess = "2.0.4"
rcgen = "0.13.0"
local-ip-address = "0.6.1"

[dependencies.echo_tree_rs]
git = "https://github.com/CJBuchel/EchoTree.git"
