[package]
name = "tms_server"
version = "2023.0.0"
edition = "2021"
authors = ["Connor J Buchel <connorbuchel@gmail.com>"]
build = "build/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tms-utils = { path = "tms-utils" }
tms-attributes = { path = "tms-attributes" }
tokio = { version = "^1.27", features = ["macros", "sync", "rt-multi-thread"] }
tokio-stream = "^0.1.9"
warp = { version = "^0.3", features = ["tls"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
futures = { version = "^0.3", default-features = false }
uuid = { version = "^1.3", features = ["serde", "v4"] }
openssl-sys = "^0.9"
openssl = { version = "^0.10", features = ["vendored"] }
pretty_env_logger = "^0.4.0"
sled = "0.34.7"
sled-extensions = { version = "0.2.0", features = ["bincode"] }
thiserror = "1.0.40"
schemars = "^0.8"
local-ip-address = "0.5.1"
mdns-sd = "0.7.2"
base64 = "0.21.0"
rocket = { version = "=0.5.0-rc.3", features = ["json"] } # use command: rustup default nightly
log = "0.4.17"


# [dependencies.rocket_contrib]
# version = "0.4.11"
# default-features = false
# features = ["json"]

[build-dependencies]
schemars = "^0.8"
anyhow = "^1.0.70"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
serde_yaml = "^0.9"