[package]
name = "tms_server"
version = "2023.0.0"
edition = "2021"
authors = ["Connor J Buchel <connorbuchel@gmail.com>"]
build = "build/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "^1.27", features = ["macros", "sync", "rt-multi-thread"] }
tokio-stream = "^0.1.9"
warp = { version = "^0.3", features = ["tls"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
futures = { version = "^0.3", default-features = false }
uuid = { version = "^1.3", features = ["serde", "v4"] }
openssl-sys = "^0.9"
openssl = { version = "^0.10", features = ["vendored"] }
pretty_env_logger = "^0.4.0"

[build-dependencies]
schemars = "^0.8"
anyhow = "^1.0.70"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"