name: tms
description: "Tournament Management System Client, for scoring and managing FLL events"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  echo_tree_flutter:
    git: 
      url: https://github.com/CJBuchel/EchoTree.git
      path: echo_tree_flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  dotenv: ^4.2.0
  flutter_dotenv: ^5.1.0
  web_socket_channel: ^2.4.4
  http: ^1.2.1
  uuid: ^4.3.3
  logger: ^2.2.0
  multicast_dns: ^0.3.2+6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true