name: tms
description: "Tournament Management System Client, for scoring and managing FLL events"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  echo_tree_flutter:
    git: 
      url: https://github.com/CJBuchel/EchoTree.git
      path: echo_tree_flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  dotenv: ^4.2.0
  flutter_dotenv: ^5.1.0
  web_socket_channel: ^2.4.4
  http: ^1.2.1
  uuid: ^4.3.3
  logger: ^2.2.0
  multicast_dns: ^0.3.2+6
  shared_preferences: ^2.2.2
  go_router: ^13.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# run -> `flutter pub run flutter_launcher_icons` to generate icons
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logos/TMS_LOGO_ICON_SQUARE.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/audio/

  fonts:
    # primary font
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900