#
# Install requirements for wasm & codegen
#
steps:
  # add wasm target for web codegen
  - task: Rustup@1
    displayName: 'Add wasm target for web codegen'
    inputs:
      rustupCommand: '+nightly'
      rustupCommandArguments: 'target add wasm32-unknown-unknown'
      verbose: false

  # Install wasm pack (check if already installed)
  - script: |
      if ! command -v wasm-pack &> /dev/null; then
        echo "Installing wasm-pack"
        cargo install wasm-pack
      else
        echo "wasm-pack is already installed"
      fi
    condition: ne(variables['Agent.OS'], 'Windows_NT')
    displayName: 'Install wasm-pack (Unix)'

  - powershell: |
      if (-not (Get-Command wasm-pack -ErrorAction SilentlyContinue)) {
        Write-Output "Installing wasm-pack"
        cargo install wasm-pack
      } else {
        Write-Output "wasm-pack is already installed"
      }
    condition: eq(variables['Agent.OS'], 'Windows_NT')
    displayName: 'Install wasm-pack (Windows)'

  # install FRB (cargo task uses manifest, using script instead)
  - script: |
      if ! command -v flutter_rust_bridge_codegen &> /dev/null; then
        echo "Installing FRB"
        cargo install flutter_rust_bridge_codegen
      else
        echo "FRB already installed"
      fi
    condition: ne(variables['Agent.OS'], 'Windows_NT')
    displayName: 'Install FRB (Unix)'

  - powershell: |
      if (-not (Get-Command flutter_rust_bridge_codegen -ErrorAction SilentlyContinue)) {
        Write-Output "Installing FRB"
        cargo install flutter_rust_bridge_codegen
      } else {
        Write-Output "FRB already installed"
      }
    condition: eq(variables['Agent.OS'], 'Windows_NT')
    displayName: 'Install FRB (Windows)'