refresh_rate: 30 seconds
appenders:

  # General Console/Terminal output
  stdout:
    kind: console
    encoder:
      pattern: "[{d(%Y-%m-%d %H:%M:%S)} {h({l})} {M} LINE: {L}] {m}{n}"

  # Rolling file appender
  tms_server:
    kind: rolling_file
    path: "logs/tms.log"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 1MB
      roller:
        kind: fixed_window
        base: 1
        count: 10
        pattern: "logs/tms.{}.log"
    encoder:
      pattern: "[{d(%Y-%m-%d %H:%M:%S)} {h({l})} {M} LINE: {L}] {m}{n}"

# Loggers
root:
  level: info
  appenders:
    - stdout
    - tms_server