parameters:
  - name: sourcePath
    type: string
  - name: contents
    type: string
    default: '**'
  - name: flattenFolders
    type: boolean
    default: false

steps:
  - task: CopyFiles@2
    displayName: 'Copy ${{ parameters.sourcePath }} to staging directory'
    inputs:
      SourceFolder: '${{ parameters.sourcePath }}'
      contents: '${{ parameters.contents }}'
      targetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: ${{ parameters.flattenFolders }}