# download env files and place correctly
steps:
  # download environment artifacts
  - task: DownloadPipelineArtifact@2
    displayName: 'Download Env Files'
    inputs:
      artifact: 'env-files'
      targetPath: '$(Pipeline.Workspace)/env-files'
  # copy .env to tms-client
  - task: CopyFiles@2
    displayName: 'Copy .env to tms-client'
    inputs:
      SourceFolder: '$(Pipeline.Workspace)/env-files'
      Contents: '.env'
      TargetFolder: '$(Pipeline.Workspace)/tms-client'
      OverWrite: true
  # copy .env to root
  - task: CopyFiles@2
    displayName: 'Copy .env to workspace'
    inputs:
      SourceFolder: '$(Pipeline.Workspace)/env-files'
      Contents: '.env'
      TargetFolder: '$(Pipeline.Workspace)'
      OverWrite: true