
parameters:
  - name: pubCachePath
    default: $(Pipeline.Workspace)/.pub-cache
#
# Caching for Flutter dependencies and build artifacts.
#
steps:
  # Cache Flutter dependencies (not windows for now)
  - task: Cache@2
    displayName: 'Cache Flutter Dependencies'
    condition: ne(variables['Agent.OS'], 'Windows_NT')
    inputs:
      key: 'flutter-pub | "$(Agent.OS)" | "$(Build.SourcesDirectory)/tms-client/pubspec.lock"'
      restoreKeys: 'flutter-pub | "$(Agent.OS)"'
      path: $(pubCachePath)

  # list out all the directory locations where pub cache could be
  - powershell: |
      dir $env:USERPROFILE
      dir $env:USERPROFILE\AppData
      dir $env:USERPROFILE\AppData\Local
      dir $env:USERPROFILE\AppData\Local\Pub
      dir $env:AGENT_TOOLSDIRECTORY
      dir $env:AGENT_TEMPDIRECTORY
    condition: eq(variables['Agent.OS'], 'Windows_NT')



  # Cache flutter build
  - task: Cache@2
    displayName: 'Cache Flutter Build'
    inputs:
      key: 'flutter-build | "$(Agent.OS)" | "$(Build.SourcesDirectory)/tms-client/pubspec.lock"'
      restoreKeys: 'flutter-build | "$(Agent.OS)"'
      path: $(Build.SourcesDirectory)/tms-client/build