#
# Caching for Flutter dependencies and build artifacts.
#
steps:
  # Cache Flutter dependencies (not windows for now)
  - task: Cache@2
    displayName: 'Cache Flutter Dependencies'
    condition: ne(variables['Agent.OS'], 'Windows_NT')
    inputs:
      key: 'flutter-pub | "$(Agent.OS)" | "$(Build.SourcesDirectory)/tms-client/pubspec.lock"'
      restoreKeys: 'flutter-pub | "$(Agent.OS)"'
      path: $(Pipeline.Workspace)/.pub-cache

  # Cache flutter build
  - task: Cache@2
    displayName: 'Cache Flutter Build'
    inputs:
      key: 'flutter-build | "$(Agent.OS)" | "$(Build.SourcesDirectory)/tms-client/pubspec.lock"'
      restoreKeys: 'flutter-build | "$(Agent.OS)"'
      path: $(Build.SourcesDirectory)/tms-client/build