
parameters:
  - name: pubCachePath
    default: $(Pipeline.Workspace)/.pub-cache
#
# Caching for Flutter dependencies and build artifacts.
#
steps:
  # Cache Flutter dependencies
  - task: Cache@2
    displayName: 'Cache Flutter Dependencies'
    inputs:
      key: 'flutter-pub | "$(Agent.OS)" | "$(Build.SourcesDirectory)/tms-client/pubspec.lock"'
      restoreKeys: 'flutter-pub | "$(Agent.OS)"'
      path: $(pubCachePath)

  # Cache flutter build
  - task: Cache@2
    displayName: 'Cache Flutter Build'
    inputs:
      key: 'flutter-build | "$(Agent.OS)" | "$(Build.SourcesDirectory)/tms-client/pubspec.lock"'
      restoreKeys: 'flutter-build | "$(Agent.OS)"'
      path: $(Build.SourcesDirectory)/tms-client/build