#
# Install requirements for flutter
#
steps:
  # Flutter install
  - task: FlutterInstall@0
    displayName: 'Install flutter'
    inputs:
      mode: 'auto'
      channel: 'stable'
      version: 'custom'
      customVersion: '3.22.2'