#
# Install requirements for flutter
#
steps:
  # Flutter install
  - task: FlutterInstall@0
    displayName: 'Install flutter'
    inputs:
      mode: 'auto'
      channel: 'stable'
      version: 'custom'
      customVersion: '3.22.2'
  # Get Flutter dependencies
  - task: FlutterCommand@0
    displayName: 'Install Flutter dependencies'
    inputs:
      projectDirectory: 'tms-client'
      arguments: 'pub get'
  
  # list out all the directory locations where pub cache could be
  - powershell: |
      dir $env:AGENT_TOOLSDIRECTORY\Flutter
      dir $env:AGENT_TEMPDIRECTORY
      dir $env:AGENT_WORKFOLDER\_temp
      dir $env:USERPROFILE
      dir $env:USERPROFILE\AppData
      dir $env:USERPROFILE\AppData\Local
      dir $env:USERPROFILE\AppData\Local\Pub
    condition: eq(variables['Agent.OS'], 'Windows_NT')