steps:
  # download the artifact
  - task: DownloadPipelineArtifact@2
    displayName: 'Download IPA Artifact'
    inputs:
      artifact: 'client-windows'
      targetPath: '$(Pipeline.Workspace)/client-windows'

  # release to the windows store
  - task: store-publish@0
    inputs:
      serviceEndpoint: 'TMS Client Windows'
      appId: '9NK7M3N9S5X7'
      packagePath: '$(Pipeline.Workspace)/**/*.msix'
      force: true
      skipPolling: false
      deletePackages: true
      numberOfPackagesToKeep: '1'
      isMandatoryUpdate: true