
jobs:
- job: Docker
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: './release-steps/release-docker-steps.yml'

- job: IOS
  condition: and(succeeded(), eq(variables['isIosPublishable'], true))
  pool:
    vmImage: 'macos-latest'
  steps:
    - template: './release-steps/release-ios-steps.yml'

# - job: Windows
#   pool:
#     vmImage: 'windows-latest'
#   steps:
#     - template: './release-steps/release-windows-steps.yml'

- job: Github
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: './release-steps/release-github-steps.yml'