
jobs:
- job: Release_AIO_Docker
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    # Download the Docker image from the pipeline artifact directory
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Pipeline Artifact'
      inputs:
        artifact: 'docker_image'
        # put the artifact in the pipeline workspace
        targetPath: '$(Pipeline.Workspace)/docker_image'
    
    # Load the Docker image from the tarball
    - script: docker load -i $(Pipeline.Workspace)/docker_image/docker_image.tar
      displayName: 'Load Docker Image from Tarball'

    - task: Docker@2
      displayName: 'Login to Docker Hub'
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)

    - task: Docker@2
      displayName: 'Push Image to Docker Hub'
      inputs:
        command: push
        repository: $(dockerRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(version)
          latest
