
jobs:
- job: Docker
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: './release-steps/release-docker-steps.yml'

# - job: IOS
#   pool:
#     vmImage: 'macos-latest'
#   steps:
#     - template: './release-steps/release-ios-steps.yml'