
jobs:
- job: Release_AIO_Docker
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Pipeline Artifact'
      inputs:
        artifact: 'docker_image'
        path: '$(Pipeline.Workspace)'

    - task: Docker@2
      displayName: 'Login to Docker Hub'
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)

    - task: Docker@2
      displayName: 'Push Image to Docker Hub'
      inputs:
        command: push
        repository: $(dockerRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(version)
          latest
