parameters:
  - name: name
    type: string
    default: 'infra'

#
# Instead of checking out the repository, we download the repository artifact
#
steps:
  - checkout: none # disable automatic checkout
  # download the repo artifact
  - task: DownloadPipelineArtifact@2
    displayName: 'Download Repo'
    inputs:
      artifact: '${{ parameters.name }}-repo-artifact'
      targetPath: '$(Build.SourcesDirectory)'