parameters:
  - name: name
    type: string
    default: 'infra'

steps:
  # publish the repo artifact
  - task: PublishBuildArtifacts@1
    displayName: 'Publish ${{ parameters.name }} Repo Artifact'
    inputs:
      PathToPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '${{ parameters.name }}-repo-artifact'