parameters:
  - name: dockerFile
    type: string

steps:
  # download the artifact
  - task: DownloadPipelineArtifact@2
    displayName: 'Download Docker Image'
    inputs:
      artifact: 'docker-image'
      targetPath: '$(Pipeline.Workspace)/docker-image'
  
  # load docker image from tarball
  - script: |
      docker load -i $(Pipeline.Workspace)/**/${{ parameters.dockerFile }}
    displayName: 'Load Docker Image'

  # tag the image
  - script: |
      docker tag $(dockerRepository):latest $(dockerRepository):$(tms_version)
    displayName: 'Tag Docker Image'
  
  - task: Docker@2
    displayName: 'Login to Docker Hub'
    inputs:
      command: login
      containerRegistry: $(dockerRegistryServiceConnection)

  - task: Docker@2
    displayName: 'Push Image to Docker Hub'
    inputs:
      command: push
      repository: $(dockerRepository)
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: |
        $(tms_version)
        latest