parameters:
  - name: dockerFile
    type: string

steps:
  - script: |
      docker save -o $(Pipeline.Workspace)/${{ parameters.dockerFile }} $(dockerRepository):latest
    displayName: 'Save Docker Image'