parameters:
  - name: dockerFile
    type: string
  - name: targetFolder
    type: string
    default: '$(Pipeline.Workspace)'

steps:
  - script: |
      docker save -o ${{ parameters.targetFolder }}/${{ parameters.dockerFile }} $(dockerRepository):latest
    displayName: 'Save Docker Image'