steps:
  - template: build-flutter-steps.yml
    parameters:
      target: windows

  # Add a PowerShell script to rename the MSIX package
  - powershell: |
      Get-ChildItem -Path $(Build.SourcesDirectory) -Filter '*.msix' -Recurse | ForEach-Object {
        Rename-Item -Path $_.FullName -NewName "tms_client.msix"
      }
    displayName: "Rename MSIX"

  - task: CopyFiles@2
    displayName: "Copy MSIX to Artifact Staging Directory"
    inputs:
      contents: '**/*.msix'
      targetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: PublishPipelineArtifact@1
    displayName: "Publish MSIX Artifact"
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'client-windows'