
steps:
  - task: Cargo@1
    displayName: 'Build Rust Server'
    inputs:
      cargoCommand: 'build --target x86_64-unknown-linux-musl --release'
      cargoWorkingDir: './server'
      verbose: true
  
  - task: FlutterBuild@0
    displayName: 'Build Flutter Client for Web'
    inputs:
      target: 'web'
      projectDirectory: './client'
      extraArgs: '--release'

  #  Build the docker image
  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: build
      Dockerfile: $(dockerfilePath)
      repository: $(dockerRepository)
      tags: latest
  
  # save the image to the artifact staging directory
  - script: docker save -o $(Build.ArtifactStagingDirectory)/docker_image.tar $(dockerRepository):latest
    displayName: 'Save Docker Image as Tarball'

  # publish the artifact
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact: docker_image'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/docker_image.tar'
      artifact: 'docker_image'