steps:
  - task: InstallAppleCertificate@2
    displayName: "Install Apple Certificate"
    inputs:
      certSecureFile: '$(p12_alias)'
      certPwd: '$(cert_pass)'
      keychain: 'temp'
      deleteCert: true

  - task: InstallAppleProvisioningProfile@1
    displayName: "Install Provisioning Profile"
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: '$(pp_alias)'
      removeProfile: true

  # Build the flutter app
  - task: FlutterBuild@0
    displayName: "Build Flutter App for IOS"
    inputs:
      target: 'ios'
      projectDirectory: './client'
      debugMode: false
      profileMode: false
      iosCodesign: false
      extraArgs: '--release'

  - task: Xcode@5
    displayName: "Generate IPA"
    inputs:
      # build options
      actions: 'build'
      xcWorkspacePath: '$(Build.SourcesDirectory)/client/ios/Runner.xcworkspace'
      scheme: 'Runner'
      sdk: 'iphoneos'
      configuration: 'release'

      # package options
      packageApp: true

      # platform
      destinationPlatformOption: 'iOS'
      destinationTypeOption: 'simulators'
      destinationSimulators: 'iPad Air (11.4)'

      # signing
      signingOption: 'manual'
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'  

      # advanced
      useXcpretty: false

  
  - task: CopyFiles@2
    displayName: "Copy IPA to Artifact Staging Directory"
    inputs:
      contents: '**/*.ipa'
      targetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: PublishPipelineArtifact@1
    displayName: "Publish IPA Artifact"
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'client-ios'