
steps:
  - template: build-flutter-steps.yml
    parameters:
      target: apk

  # Add a bash script to rename the APK
  - script: |
      for apk in $(find $(Build.SourcesDirectory) -name '*.apk'); do
        mv "$apk" "$(dirname "$apk")/tms_client.apk"
      done
    displayName: "Rename APK"
  
  - task: CopyFiles@2
    displayName: "Copy APK to Artifact Staging Directory"
    inputs:
      contents: '**/flutter-apk/**/*.apk'
      targetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: PublishPipelineArtifact@1
    displayName: "Publish APK Artifact"
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'client-android'