steps:
  - task: InstallAppleCertificate@2
    displayName: "Install Apple Certificate"
    inputs:
      certSecureFile: '$(p12_alias)'
      certPwd: '$(cert_pass)'
      keychain: 'temp'
      deleteCert: true

  - task: InstallAppleProvisioningProfile@1
    displayName: "Install Provisioning Profile"
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: '$(pp_alias)'
      removeProfile: true

  # Prepare exportOptions.plist by injecting the provisioning profile UUID and signing identity
  - script: |
      /usr/libexec/PlistBuddy -c "Set :provisioningProfiles:a.loose.screw.tms $(APPLE_PROVISIONING_PROFILE_UUID)" "$(Build.SourcesDirectory)/client/ios/Runner/exportOptions.plist"
      /usr/libexec/PlistBuddy -c "Set :signingCertificate $(APPLE_CERTIFICATE_SIGNING_IDENTITY)" "$(Build.SourcesDirectory)/client/ios/Runner/exportOptions.plist"
    displayName: 'Configure exportOptions.plist'

  # Build the flutter app
  - task: FlutterBuild@0
    displayName: "Build Flutter App for IOS"
    inputs:
      target: 'ios'
      projectDirectory: './client'
      debugMode: false
      profileMode: false
      iosCodesign: false
      extraArgs: '--release'

  - task: Xcode@5
    displayName: "Generate IPA"
    inputs:
      actions: 'archive'
      configuration: 'Release'
      xcWorkspacePath: '$(Build.SourcesDirectory)/client/ios/Runner.xcworkspace'
      scheme: 'Runner'
      sdk: 'iphoneos'

      # package options
      packageApp: true
      archivePath: '$(Build.ArtifactStagingDirectory)/Runner.xcarchive'
      exportPath: '$(Build.ArtifactStagingDirectory)'
      exportOptions: 'plist'
      exportOptionsPlist: '$(Build.SourcesDirectory)/client/ios/Runner/exportOptions.plist'

      # signing
      signingOption: 'manual'

      # advanced
      useXcpretty: false

  
  - task: CopyFiles@2
    displayName: "Copy IPA to Artifact Staging Directory"
    inputs:
      contents: '**/*.ipa'
      targetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: PublishPipelineArtifact@1
    displayName: "Publish IPA Artifact"
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'client-ios'