jobs:
  - job: LinuxBuild
    displayName: 'Linux Server'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      # Get cache if available
      - template: rust-steps/rust-cache.yml
      - template: flutter-steps/flutter-cache.yml
      # Install requirements for rust & flutter
      - template: rust-steps/install-rust.yml
      - template: flutter-steps/install-flutter.yml
      # install wasm target and codegen
      - template: rust-steps/install-codegen.yml
      # install release targets
      - template: rust-steps/install-release-targets.yml
      # Generate the Dart code from the Rust code
      - template: rust-steps/generate-dart-code.yml
      # Build the Rust server
      - template: rust-steps/build-server.yml
      # build the Flutter web app
      - template: flutter-steps/build-client-target.yml
        parameters:
          target: 'web'

  - job: WindowsBuild
    displayName: 'Windows Server'
    pool:
      vmImage: 'windows-latest'
    steps:
      # Get rust cache if available
      - template: rust-steps/rust-cache.yml
        parameters:
          cargoPath: $(UserProfile)/.cargo
          rustupPath: $(UserProfile)/.rustup
      # Flutter cache
      - template: flutter-steps/flutter-cache.yml
        parameters:
          pubCachePath: $(UserProfile)/AppData/Local/Pub/Cache
      # Install requirements for rust & flutter
      - template: rust-steps/install-rust.yml
      - template: flutter-steps/install-flutter.yml
      # install wasm target and codegen
      - template: rust-steps/install-codegen.yml
      # install release targets
      - template: rust-steps/install-release-targets.yml
      # Generate the Dart code from the Rust code
      - template: rust-steps/generate-dart-code.yml
      # Build the Rust server
      - template: rust-steps/build-server.yml
      # build the Flutter web app
      - template: flutter-steps/build-web.yml

  - job: IosBuild
    displayName: 'iOS Client'
    pool:
      vmImage: 'macos-12'
    steps:
      # Get rust cache if available
      - template: rust-steps/rust-cache.yml
      # Flutter cache
      - template: flutter-steps/flutter-cache.yml
      # Install requirements for rust & flutter
      - template: rust-steps/install-rust.yml
      - template: flutter-steps/install-flutter.yml
      # install wasm target and codegen
      - template: rust-steps/install-codegen.yml
      # Generate the Dart code from the Rust code
      - template: rust-steps/generate-dart-code.yml
      # build the Flutter web app
      - template: flutter-steps/build-client-target.yml
        parameters:
          target: 'ios'