jobs:
  - job: LinuxBuild
    displayName: 'Linux Server'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      # server build template
      - template: templates/server-build-template.yml
      # publish artifacts template
      - template: templates/server-artifact-template.yml
        parameters:
          serverBinaryPath: '**/tms_server'
          artifactName: 'tms-linux'
          archiveType: 'tar'
          tarCompression: 'gz'
          archiveFile: 'tms.tar.gz'

  - job: WindowsBuild
    displayName: 'Windows Server'
    pool:
      vmImage: 'windows-latest'
    steps:
      # server build template
      - template: templates/server-build-template.yml
        parameters:
          cargoPath: $(UserProfile)/.cargo
          rustupPath: $(UserProfile)/.rustup
          pubCachePath: $(UserProfile)/AppData/Local/Pub/Cache
      # publish artifacts template
      - template: templates/server-artifact-template.yml
        parameters:
          serverBinaryPath: '**/tms_server.exe'
          artifactName: 'tms-windows'
          archiveType: 'zip'
          archiveFile: 'tms.zip'

  - job: IosBuild
    displayName: 'iOS Client'
    pool:
      vmImage: 'macos-14' # macos-latest isn't always latest (we need xcode 15)
    steps:
      # build client template
      - template: templates/client-build-template.yml
        parameters:
          flutterTarget: 'ios'
          buildIpa: true
      # publish artifacts template
      - template: templates/client-artifact-template.yml
        parameters:
          clientBinaryPath: '***/*.ipa'
          artifactName: 'ios-ipa'

  - job: AndroidBuild
    displayName: 'Android Client'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      # build client template
      - template: templates/client-build-template.yml
        parameters:
          flutterTarget: 'apk'
      # publish artifacts template
      - template: templates/client-artifact-template.yml
        parameters:
          clientBinaryPath: '**/flutter-apk/**/*.apk'
          artifactName: 'android-apk'