jobs:
  - job: LinuxBuild
    displayName: 'Linux Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      # Get cache if available
      - template: rust-steps/rust-cache.yml
      - template: flutter-steps/flutter-cache.yml
      # Install requirements for rust & flutter
      - template: rust-steps/install-rust.yml
      - template: flutter-steps/install-flutter.yml
      # install wasm target and codegen
      - template: rust-steps/install-wasm.yml
      # install release targets
      - template: rust-steps/install-release-targets.yml
      # Generate the Dart code from the Rust code
      - template: rust-steps/generate-dart-code.yml
      # Build the Rust server
      - template: rust-steps/build-release.yml
      # build the Flutter web app
      - template: flutter-steps/build-release.yml

  - job: WindowsBuild
    displayName: 'Windows Build'
    pool:
      vmImage: 'windows-latest'
    steps:
      # Get rust cache if available
      # - template: rust-steps/rust-cache.yml
      #   parameters:
      #     cargoPath: $(UserProfile)/.cargo
      #     rustupPath: $(UserProfile)/.rustup
      # Flutter cache
      - template: flutter-steps/flutter-cache.yml
        parameters:
          pubCachePath: $(UserProfile)/AppData/Local/Pub/Cache
      # Install requirements for rust & flutter
      # - template: rust-steps/install-rust.yml
      - template: flutter-steps/install-flutter.yml
      # install wasm target and codegen
      # - template: rust-steps/install-wasm.yml
      # install release targets
      # - template: rust-steps/install-release-targets.yml
      # Generate the Dart code from the Rust code
      # - template: rust-steps/generate-dart-code.yml
      # Build the Rust server
      # - template: rust-steps/build-release.yml
      # build the Flutter web app
      # - template: flutter-steps/build-release.yml