jobs:
  # Deploy artifacts to Github
  - deployment: DeployGithub
    displayName: 'Deploy TMS'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'tms-prod'
    strategy:
      runOnce:
        deploy:
          steps:
            # Release to github
            - template: github-steps/publish-all-to-github.yml
  # Deploy iOS app to TestFlight
  - deployment: DeployTestFlight
    displayName: 'Deploy to TestFlight'
    pool:
      vmImage: 'macOS-latest'
    environment: 'tms-prod'
    strategy:
      runOnce:
        deploy:
          steps:
            # Release to test flight
            - template: apple-steps/publish-to-testflight.yml