jobs:
  # Deploy artifacts to Github
  - deployment: DeployGithub
    displayName: 'Deploy to Github'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'tms-prod'
    strategy:
      runOnce:
        deploy:
          steps:
            # Release to github
            - template: templates/steps/github-steps/publish-all-to-github.yml
  # Deploy iOS app to TestFlight
  - deployment: DeployTestFlight
    displayName: 'Deploy to TestFlight'
    pool:
      vmImage: 'macOS-latest'
    environment: 'tms-prod'
    strategy:
      runOnce:
        deploy:
          steps:
            # Release to test flight
            - template: templates/steps/apple-steps/publish-to-testflight.yml
  # Deploy to DockerHub
  - deployment: DeployDocker
    displayName: 'Deploy to DockerHub'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'tms-prod'
    strategy:
      runOnce:
        deploy:
          steps:
            # Release to dockerhub
            - template: templates/steps/docker-steps/publish-to-dockerhub.yml