jobs:
  - job: GithubRelease
    displayName: 'Publish to Github'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      # Release to github
      - template: github-steps/publish-all-to-github.yml
  - job: iOSRelease
    displayName: 'Publish to TestFlight'
    pool:
      vmImage: 'macOS-latest'
    steps:
      # print out contents of pubpsec.yaml
      - script: |
          cat tms-client/pubspec.yaml
        displayName: 'Print pubspec.yaml'
      # Release to test flight
      - template: apple-steps/publish-to-testflight.yml